# Generated by Django 4.1 on 2023-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_sivangangai_thanjavur_thiruvallur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sivangangai',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thanjavur',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thiruvallur',
            name='size',
            field=models.IntegerField(),
        ),
    ]
