# Generated by Django 4.1 on 2023-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
