# Generated by Django 4.1 on 2023-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_sivangangai_are_thanjavur_are_thiruvallur_are'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sivangangai',
            name='are',
            field=models.CharField(default='Sivagangai', max_length=2080),
        ),
        migrations.AlterField(
            model_name='thanjavur',
            name='are',
            field=models.CharField(default='Thanjavur', max_length=2080),
        ),
        migrations.AlterField(
            model_name='thiruvallur',
            name='are',
            field=models.CharField(default='Thirvallur', max_length=2080),
        ),
    ]
