# Generated by Django 4.1 on 2023-03-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_alter_sivangangai_are_alter_thanjavur_are_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thiruvallur',
            name='are',
            field=models.CharField(default='Thiruvallur', max_length=2080),
        ),
    ]
